### ISSUE TITLE
the example program doesn't work properly

### ISSUE THREAD

**Issue by PonyTang3** [getlantern/systray#101]
I build the example program by using 'go build'. When I clicked the changeme menu, it would quit. When I clicked the ignore menu, it had panic error. I didn't  know what the problem is. What had I miss?
![QQ图片20191119161520](https://user-images.githubusercontent.com/16270359/69129323-15f11400-0ae9-11ea-806f-4e57475ebe27.png)

**Comment by PonyTang3** [comment]
```bat
@echo OFF
set CGO_ENABLED=1
set GOOS=windows
set GOARCH=386
go build -ldflags -H=windowsgui
```
When I build like that, it didn't show panic error any more. But the menus were disappeared after I click one menu.

**Comment by oxtoacart** [comment]
Does it exit when you click any menu item, or just some of them?

**Comment by PonyTang3** [comment]
> Does it exit when you click any menu item, or just some of them?
some, the changeme menu

**Comment by PonyTang3** [comment]
> > Does it exit when you click any menu item, or just some of them?
> 
> Some, just like the changeme menu. The check menu is ok.

> the example_windows_386.exe in the repo program is ok.

**Comment by joesis** [comment]
Which version of Go you were using @PonyTang3 ?

**Comment by PonyTang3** [comment]
> Which version of Go you were using @PonyTang3 ?

1.13
And I had try 1.12. The problem remains the same @joesis

**Comment by joesis** [comment]
Thanks @PonyTang3 what if you `git checkout baeca33b8639173043ac745aba9800cfbafb9cd1` and try again?

**Comment by ldstein** [comment]
For what its worth, I'm experiencing the deadlock as @PonyTang3.

I added a hack to `addOrUpdateMenuItem(item *MenuItem)` which solved the issue:

```
func addOrUpdateMenuItem(item *MenuItem) {
	action := actions[item.id]
	if action == nil {
		item.id = atomic.AddInt32(&nextActionId, 1)
		action = walk.NewAction()
		action.Triggered().Attach(func() {

			// Hack start - Ensure item.ClickedCh has at least one receiver to prevent deadlock
			go func() {
				select {
				case <-item.ClickedCh:
				}
			}()
			// Hack end

			item.ClickedCh <- struct{}{}
		})
		if err := notifyIcon.ContextMenu().Actions().Add(action); err != nil {
			fail("Unable to add menu item to systray", err)
		}
		actions[item.id] = action
	}...
```

**Comment by PonyTang3** [comment]
> git checkout baeca33b8639173043ac745aba9800cfbafb9cd1

After that, it was the same.

**Comment by PonyTang3** [comment]
> Thanks @PonyTang3 what if you `git checkout baeca33b8639173043ac745aba9800cfbafb9cd1` and try again?

After that, it was the same. @joesis

**Comment by PonyTang3** [comment]
> Thanks @PonyTang3 what if you `git checkout baeca33b8639173043ac745aba9800cfbafb9cd1` and try again?

After I checkout `baeca33b8639173043ac745aba9800cfbafb9cd1` for `$GOPATH/src/github.com/getlantern/systray`, it works. @joesis

**Comment by joesis** [comment]
Cool thanks @PonyTang3 ! So it looks like a regression by https://github.com/getlantern/systray/pull/97

**Comment by PonyTang3** [comment]
> For what its worth, I'm experiencing the same deadlock as @PonyTang3.
> 
> I added a hack to `systray_windows.go` which solved the issue (for me):
> 
> ```go
> func addOrUpdateMenuItem(item *MenuItem) {
> 	action := actions[item.id]
> 	if action == nil {
> 		item.id = atomic.AddInt32(&nextActionId, 1)
> 		action = walk.NewAction()
> 		action.Triggered().Attach(func() {
> 
> 			// Hack start - Ensure item.ClickedCh has at least one receiver to prevent deadlock
> 			go func() {
> 				select {
> 				case <-item.ClickedCh:
> 				}
> 			}()
> 			// Hack end
> 
> 			item.ClickedCh <- struct{}{}
> 		})
> 		if err := notifyIcon.ContextMenu().Actions().Add(action); err != nil {
> 			fail("Unable to add menu item to systray", err)
> 		}
> 		actions[item.id] = action
> 	}...
> ```

It had no deadlock error after that, but it would still quit when I clicked changeme button. @ldstein

**Comment by ldstein** [comment]
Oh right - that's another issue I had to work around. Adding `systray.AddSeparator()` as the first item puts the clicks handlers back in the correct order:

```go
go func() {
		systray.SetIcon(icon.Data)
		systray.SetTitle("Awesome App")
		systray.SetTooltip("Pretty awesome棒棒嗒")
		// Hack Start - Add a separator to work around click order bug
		systray.AddSeparator()
		// Hack End
		mChange := systray.AddMenuItem("Change Me", "Change Me")
		mChecked := systray.AddMenuItem("Unchecked", "Check Me")
		mEnabled := systray.AddMenuItem("Enabled", "Enabled")
```

**Comment by PonyTang3** [comment]
> > Thanks @PonyTang3 what if you `git checkout baeca33b8639173043ac745aba9800cfbafb9cd1` and try again?
> 
> After I checkout `baeca33b8639173043ac745aba9800cfbafb9cd1` for `$GOPATH/src/github.com/getlantern/systray`, it works. @joesis

It se

> Cool thanks @PonyTang3 ! So it looks like a regression by #97

Without #97, I can build by `go build -tags walk_use_cgo`.

**Comment by oxtoacart** [comment]
Thanks @ldstein, I've merged your fix.

@PonyTang3 does it work correctly for you now?

**Comment by PonyTang3** [comment]
> Thanks @ldstein, I've merged your fix.
> 
> @PonyTang3 does it work correctly for you now?

It works now. But I can't build the program by using `go build -tags walk_use_cgo`

**Comment by oxtoacart** [comment]
@PonyTang3 What happens if you try

`CGO_ENABLED=1 go build -tags walk_use_cgo`

?

**Comment by PonyTang3** [comment]
> @PonyTang3 What happens if you try
> 
> `CGO_ENABLED=1 go build -tags walk_use_cgo`
> 
> ?

`CGO_ENABLED=1` is my default env.  @oxtoacart 

```bat
@echo OFF
go clean
set CGO_ENABLED=1
set GOOS=windows
set GOARCH=386
go build -tags walk_use_cgo
```

![image](https://user-images.githubusercontent.com/16270359/69292545-5f547700-0c41-11ea-8d93-8810fd38c1cf.png)

**Comment by oxtoacart** [comment]
@PonyTang3 For some strange reason, `go build` looks like it might be trying to build something it shouldn't be. If I build `main.go` instead, it works for me:

`CGO_ENABLED=1 go build -tags walk_use_cgo main.go`
