### ISSUE TITLE
hanging app when item clicking

### ISSUE THREAD

**Issue by vizzyolog** [getlantern/systray#116]
this does not happen every time, but more often when in parallel goroutine are heavy processes. Can anyone encountered the same problem? 
The error can occur when you click on an item that does not cause anything only
`
case <-itemJustItem.ClickedCh:
				fmt.Println("JustItemClicked")
`

When start with debugger I see - 
`
func gopark(unlockf func(*g, unsafe.Pointer) bool, lock unsafe.Pointer, reason waitReason, traceEv byte, traceskip int) {
	if reason != waitReasonSleep {
		checkTimeouts() // timeouts may expire while two goroutines keep the scheduler busy
	}
	mp := acquirem()
	gp := mp.curg
	status := readgstatus(gp)
	if status != _Grunning && status != _Gscanrunning {
		throw("gopark: bad g status")
	}
	mp.waitlock = lock
	mp.waitunlockf = *(*unsafe.Pointer)(unsafe.Pointer(&unlockf))
	gp.waitreason = reason
	mp.waittraceev = traceEv
	mp.waittraceskip = traceskip
	releasem(mp)
	// can't do anything that might move the G between Ms here.
	mcall(park_m)
}
`
in console - 
 `JustItemClicked
Failed to next - thread blocked`

**Comment by joesis** [comment]
Did you call `systray.Run` at the very beginning of `main`, as the README suggests?

**Comment by vizzyolog** [comment]
Yes I do.  It in very very beginning )
I solved my problem by limiting the number of SetTitle() in time. Now it doesn't hang.

Thank you for package it is very useful for me.
