### ISSUE TITLE
Systray requires admin-rights on Windows when installed in program files

### ISSUE THREAD

**Issue by netras** [getlantern/systray#127]
With the current version of systray, I cannot run my installed application on Windows without administrative permissions. Reason: Systray attempts to store the icon file inside the application directory.

> panic: Unable to save icon to disk: open C:\Program Files\[MyApp]\systray.78ab1d2dac477997ecd76010880359c7.ico: Access is denied.
> 
> goroutine 34 [running]:
> github.com/getlantern/systray.fail(...)
> 	C:/Users/venoran/nextcloud/go/src/github.com/getlantern/systray/systray_windows.go:218

Looking through commits for systray, it appears that previously the temp directory was used to store icon files. This worked because it does not require elevated permissions in Windows.

If it is necessary to read icon files from disk, I could place icon files in the application directory myself during installation and systray could read those. Alternatively, using an option for using temp (or any specified) directory would also work for me as I could use user-accessible dirs.

Is this is a known issue? Am I doing something wrong?

Any feedback would be appreciated. Thank you for working on this. It is a great help to me.

**Comment by netras** [comment]
I played around a bit and found that I can provide icon paths to `notifyIcon` directly without having to write these files to disk first.

I have added this function to `systray_windows.go`
> func SetIconFromFile(filePath string) error {
> 	icon, err := walk.Resources.Icon(filePath)
> 	if err != nil {
> 		return err
> 	}
> 	if err := notifyIcon.SetIcon(icon); err != nil {
> 		return err
> 	}
> 	if err := notifyIcon.SetVisible(true); err != nil {
> 		return err
> 	}
> 	return nil
> }

This worked well in my test cases even with animations (switching icons every 250 ms). And because I provide icon files with my installation routine, no elevated permissions are required when executing the application.

Would that be an option worth keeping for the package in general?

**Comment by Kimbsen** [comment]
You can also set a custom path to store the icon file by importing "github.com/lxn/walk" and calling 
```walk.Resources.SetRootDirPath()``` before calling ```systray.SetIcon()```

This avoids the permission issue when running from programfiles or any other restricted location.

**Comment by netras** [comment]
> 
> 
> You can also set a custom path to store the icon file by importing "github.com/lxn/walk" and calling `walk.Resources.SetRootDirPath()` before calling `systray.SetIcon()`
> 
> This avoids the permission issue when running from programfiles or any other restricted location.

That should definitely work and would solve my issue. Thank you for the suggestion.

The only downside is that it feels a bit wasteful to store icons hardcoded as byte slices, writing them to disk during execution, then reading them back to memory to then apply them to the tray (and cleaning the files afterwards).

If I can provide the files on disk to begin with, I remove a few steps and do not need to clean up afterwards. It sounds like a good option to have.

**Comment by max-b** [comment]
@netras will this work for you? https://github.com/getlantern/systray/pull/129

It's a little unclear to me whether/how plausible it would be to write byte slices directly to the underlying `walk` framework, but if you want to take a look, that would be an interesting option.

**Comment by netras** [comment]
> 
> 
> @netras will this work for you? #129 

I´ve just tested the change and it works again properly on Windows. Thank you for providing a solution.

> 
> It's a little unclear to me whether/how plausible it would be to write byte slices directly to the underlying `walk` framework, but if you want to take a look, that would be an interesting option.

I think you misunderstood my suggestion.
`systray.SetIcon` takes an icon as byte slices and, if not already there (e. g. cache miss), writes it to disk so that it can be read from disk again by `walk.Resources.Icon`.

My suggestion was not to write byte slices to `walk` but to add an `SetIconFromFile` option/function to `systray`. If ico-files are already on disk (in case of an packaged/installed application), they do not need to be written to disk first and can immediately be read by `walk.Resources.Icon` without any temporary directory/files. This is probably not useful to everybody but would be a good option at least in my use case.

**Comment by max-b** [comment]
I'd like to close this for now. I'm not sure we have the resources atm, but if you'd like to propose the `SetIconFromFile` solution in another issue/PR we can try and think that through there.


Thanks!
