### ISSUE TITLE
Dynamic icon support

### ISSUE THREAD

**Issue by games647** [getlantern/systray#13]
Is it possible to make a dynamic tray icon which will be painted during runtime?

**Comment by slaveriq** [comment]
You can change the tray icon at runtime. 
[Example/main.go](https://github.com/getlantern/systray/blob/master/example/main.go#L28)

I have in one of my projects used it to indicate and error like so:
```
if err != nil {
    systray.SetIcon(icon.Error)
   // Handle error
}
```
The icon package then ofc needs to have an icon named Error.

**Comment by games647** [comment]
Thanks it worked out. I'm currently using this to draw an image and update it.

```go
	buf := new(bytes.Buffer)
	err := jpeg.Encode(buf, img, nil)
	if err != nil {
		log.Fatal(err)
	}

	data = buf.Bytes()
```
