### ISSUE TITLE
Proposed API

### ISSUE THREAD

**Issue by nojus297** [getlantern/systray#136]
Hello.
While your `systray` seems to be the most feature rich go tray library out there, I still find it's API inconsistent and not so trivial to use. Therefore I tried to design a solid API (that I would at least like myself).
I know that this means a complete rewrite of the core code and broken backwards compatibility. Therefore I wanted to ask whether you would agree on this or you would rather stick with the current one. If not, I would probably create my own package. 
I have pretty much fully implemented this on linux.
Anyway, here is the proposed API (which is not yet perfect of course):
```
    type Menu
        func NewMenu() *Menu
        func (m *Menu) Append(item *MenuItem) *Menu
        func (m *Menu) Clear() *Menu
        func (m *Menu) Hide(item *MenuItem) *Menu
        func (m *Menu) InsertAfter(new, existing *MenuItem) *Menu
        func (m *Menu) InsertBefore(new, existing *MenuItem) *Menu
        func (m *Menu) Parent() *MenuItem
        func (m *Menu) Prepend(item *MenuItem) *Menu
        func (m *Menu) Remove(item *MenuItem) *Menu
        func (m *Menu) SetHandler(handler func(*MenuItem)) *Menu
        func (m *Menu) Show(item *MenuItem) *Menu
        func (m *Menu) Visible(item *MenuItem) bool
    type MenuItem
        func NewMenuItem(label string) *MenuItem
        func NewSeparator() *MenuItem
        func (mi *MenuItem) Check() *MenuItem
        func (mi *MenuItem) Checked() bool
        func (mi *MenuItem) Disable() *MenuItem
        func (mi *MenuItem) Enable() *MenuItem
        func (mi *MenuItem) Enabled() bool
        func (mi *MenuItem) Parent() *Menu
        func (mi *MenuItem) SetCheckable(checkable bool) *MenuItem
        func (mi *MenuItem) SetHandler(handler func()) *MenuItem
        func (mi *MenuItem) SetIcon(icon []byte) *MenuItem
        func (mi *MenuItem) SetLabel(label string) *MenuItem
        func (mi *MenuItem) SetSubmenu(submenu *Menu) *MenuItem
        func (mi *MenuItem) Submenu() *Menu
        func (mi *MenuItem) Uncheck() *MenuItem
    type Tray
        func NewTray() *Tray
        func (t *Tray) Menu() *Menu
        func (t *Tray) Quit()
        func (t *Tray) Run() *Tray
        func (t *Tray) SetIcon(icon []byte) *Tray
        func (t *Tray) SetTitle(title string) *Tray
        func (t *Tray) SetTooltip(tooltip string) *Tray
        func (t *Tray) Wait() *Tray
```

**Comment by joesis** [comment]
This looks comprehensive but I'd rather prefer keeping the API minimum. For example, is there a need to create more than one `Tray`? Is it necessary to dynamically adjusting the order of menu items? I'd like to see requirements popping up from the field before adding any of them.

**Comment by nojus297** [comment]
> For example, is there a need to create more than one Tray?
The main reason for me is the ability to pass the Tray object around.
But I see your point, so I close this issue.
