### ISSUE TITLE
the webview in systray.ShowAppWindow  is not the default  ie version in windows?

### ISSUE THREAD

**Issue by hick** [getlantern/systray#138]
![image](https://user-images.githubusercontent.com/38886/80298294-543bdf00-87bd-11ea-83b3-e4d9a05b477d.png)

MSIE7  means it is MS internet explorer 7 , AKA IE7 ?    my windows is windows 7 and the default IE version is 11,    many js lib is not compatible  with this version.   any way to change it to the default systerm IE version?  

![image](https://user-images.githubusercontent.com/38886/80298302-7df50600-87bd-11ea-8372-0dcd9727f05a.png)

**Comment by joesis** [comment]
Unfortunately since 1.0.0 systray dropped support for webview, but it does have a `webview_example` to show how it can work together with webview tools. The example uses `lxn/walk` on Windows. You may need to check the `lxn/walk` project for details.
