### ISSUE TITLE
Required library libxapp-dev

### ISSUE THREAD

**Issue by haroflow** [getlantern/systray#141]
I'm on Linux Mint 19.3, kernel 5.3.0-51-generic, and following the guide I coudn't get the library to work, even after installing the dependencies. I was getting this error:
```
$ go get 
# pkg-config --cflags  -- gtk+-3.0 webkit2gtk-4.0 appindicator3-0.1
Package xapp was not found in the pkg-config search path.
Perhaps you should add the directory containing `xapp.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xapp', required by 'appindicator3-0.1', not found
pkg-config: exit status 1
```

After installing libxapp-dev everything worked.
```
sudo apt-get install libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev libxapp-dev
```

Thank you!

**Comment by joesis** [comment]
Interesting so installing `appindicator3-0.1` doesn't install `xapp` which is one of its dependencies?

**Comment by haroflow** [comment]
I'm not sure... But I had problems with systray with electron-js as well...

I think it's some Mint+Cinnamon+appindicator craziness. There's even a configuration to "enable support of indicator icons on notification area" which seems to change something, just don't know what.
![image](https://user-images.githubusercontent.com/4776931/81711623-3a9bc800-944a-11ea-8d07-ce8ec39e9f36.png)

Here's the packages found for appindicator:
```
$ dpkg -l | grep appindicator
ii  gir1.2-appindicator3-0.1                   12.10.1+18.04.20180322.1-1mint2                  amd64        Typelib files for libappindicator3-1.
ii  libappindicator3-1                         12.10.1+18.04.20180322.1-1mint2                  amd64        Application Indicators
ii  libappindicator3-dev                       12.10.1+18.04.20180322.1-1mint2                  amd64        Application Indicators
```

I removed libxapp-dev, installed appindicator3-0.1, and this is the result:
```
$ go get
# testes/teste_systray
/home/seti/go/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lxapp
collect2: error: ld returned 1 exit status
```
The same happens when trying to run my main.go...

Then I reinstalled libxapp-dev and everything started working again...

**Comment by joesis** [comment]
Thanks @haroflow ! I don't have much experience on such stuff but as you noticed it I think adding another requirement in README would be good enough.

**Comment by joesis** [comment]
@haroflow can you post the result of the following command from your machine?

```
sudo apt-cache depends appindicator3-0.1 libappindicator3-dev
```

**Comment by haroflow** [comment]
Sure!

```
$ sudo apt-cache depends appindicator3-0.1 libappindicator3-dev
gir1.2-appindicator3-0.1
  Depends: gir1.2-glib-2.0
  Depends: gir1.2-gtk-3.0
  Depends: libappindicator3-1
gir1.2-ayatanaappindicator3-0.1
  Depends: gir1.2-glib-2.0
  Depends: gir1.2-gtk-3.0
  Depends: libayatana-appindicator3-1
libappindicator3-0.1-cil
  Depends: cli-common
  Depends: libappindicator3-1
  Depends: libglib3.0-cil
  Depends: libgtk3.0-cil
  Depends: libmono-corlib4.5-cil
  Depends: libc6
libappindicator3-0.1-cil-dev
  Depends: libappindicator3-0.1-cil
monodoc-appindicator3-0.1-manual
  Depends: monodoc-manual
libappindicator3-dev
  Depends: gir1.2-appindicator3-0.1
  Depends: libdbusmenu-glib-dev
  Depends: libdbus-glib-1-dev
  Depends: libgtk-3-dev
  Depends: libappindicator3-1
```

libappindicator3-1 seems to depend on libxapp1, though...
```
$ sudo apt-cache depends  libappindicator3-1
libappindicator3-1
  PreDepends: multiarch-support
    multiarch-support:i386
  Depends: libc6
  Depends: libdbusmenu-glib4
  Depends: libdbusmenu-gtk3-4
  Depends: libglib2.0-0
  Depends: libgtk-3-0
  Depends: libindicator3-7
  Depends: libxapp1
  Suggests: indicator-application
```

**Comment by haroflow** [comment]
Just tested on a fresh Mint install (http://mirrors.evowise.com/linuxmint/stable/19.3/linuxmint-19.3-cinnamon-64bit.iso)...

- Cloned the repo
- Installed dependencies `sudo apt-get install libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev`
- Ran the example and it showed me the same problem...
- Tried installing appindicator3-0.1,  libxapp1 again, didn't work...
- Installed libxapp-dev and it worked...

Full terminal session here: https://pastebin.com/BY4bYXDY

**Comment by joesis** [comment]
Thanks for the find and help on reproducing @haroflow . Will mention the requirement of `libxapp-dev` on Mint in README.

**Comment by joesis** [comment]
47979e9a
