### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by rajkumarks7** [getlantern/systray#142]
you wrote a example but i am unable to change the icon of the example how can i do that? in linux ubuntu

**Comment by joesis** [comment]
Check the `example/icon` directory

**Comment by rajkumarks7** [comment]
when i try to replace the icon it is not working. i am unable to understand the files present in it like iconwin.ico all those in which data is saved. i tryed by replacing the icons with my own icons in it. it is not working.

**Comment by rajkumarks7** [comment]
> Check the `example/icon` directory

can you give a example of it is not working when i replace it with my own icon in the above directory.

**Comment by joesis** [comment]
Did you see the `makeicon.sh` and `makeicon.bat`? They are scripts on corresponding platforms to generate go files to be included in the example.

**Comment by rajkumarks7** [comment]
ok i saw them but i did not understand what are those files i did a thing like run your example code and 
did a thing like i changed the icons in the examples with my own icons but it is not working.

**Comment by joesis** [comment]
Change the icon file and run the script to change the go file, then you should be able see the changes. By checking carefully the `main.go` you should be able to see where the `iconData` comes from.

**Comment by rajkumarks7** [comment]
yes sir i changed the icon i replaced both the icon.png file and iconwin.ico file but it is not showing any icon but it worked perfectly with your icon sir.
