### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by mangalaman93** [getlantern/systray#148]
```
ERROR systray: systray_windows.go:795 Unable to set icon: The operation completed successfully. [error=Unable to set icon: %v error_location=github.com/getlantern/systray.SetIcon (systray_windows.go:795) error_op= error_text=Unable to set icon: The operation completed successfully. error_type=errors.Error]
ERROR systray: systray_windows.go:795   at github.com/getlantern/systray.SetIcon (systray_windows.go:795)
ERROR systray: systray_windows.go:795   at github.com/mangalaman93/giggle/tray.(*GTray).OnReady (tray.go:63)
ERROR systray: systray_windows.go:795   at github.com/getlantern/systray.Register.func2 (systray.go:89)
ERROR systray: systray_windows.go:795   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:795 Caused by: The operation completed successfully.
ERROR systray: systray_windows.go:853 Unable to set tooltip: Unspecified error [error=Unable to set tooltip: %v error_location=github.com/getlantern/systray.SetTooltip (systray_windows.go:853) error_op= error_text=Unable to set tooltip: Unspecified error error_type=errors.Error]
ERROR systray: systray_windows.go:853   at github.com/getlantern/systray.SetTooltip (systray_windows.go:853)
ERROR systray: systray_windows.go:853   at github.com/mangalaman93/giggle/tray.(*GTray).OnReady (tray.go:64)
ERROR systray: systray_windows.go:853   at github.com/getlantern/systray.Register.func2 (systray.go:89)
ERROR systray: systray_windows.go:853   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:853 Caused by: Unspecified error
ERROR systray: systray_windows.go:861 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861) error_op= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.(*MenuItem).update (systray.go:192)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.AddMenuItem (systray.go:114)
ERROR systray: systray_windows.go:861   at github.com/mangalaman93/giggle/tray.(*GTray).OnReady (tray.go:66)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.Register.func2 (systray.go:89)
ERROR systray: systray_windows.go:861   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:861 Caused by: Invalid menu handle.
ERROR systray: systray_windows.go:831 Unable to load icon from temp file: The operation completed successfully. [error=Unable to load icon from temp file: %v error_location=github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:831) error_op= error_text=Unable to load icon from temp file: The operation completed successfully. error_type=errors.Error]
ERROR systray: systray_windows.go:831   at github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:831)
ERROR systray: systray_windows.go:831   at github.com/mangalaman93/giggle/tray.(*GTray).OnReady (tray.go:67)
ERROR systray: systray_windows.go:831   at github.com/getlantern/systray.Register.func2 (systray.go:89)
ERROR systray: systray_windows.go:831   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:831 Caused by: The operation completed successfully.
ERROR systray: systray_windows.go:861 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861) error_op= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.(*MenuItem).update (systray.go:192)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.AddMenuItem (systray.go:114)
ERROR systray: systray_windows.go:861   at github.com/mangalaman93/giggle/tray.(*GTray).OnReady (tray.go:69)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.Register.func2 (systray.go:89)
ERROR systray: systray_windows.go:861   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:861 Caused by: Invalid menu handle.
ERROR systray: systray_windows.go:831 Unable to load icon from temp file: The operation completed successfully. [error=Unable to load icon from temp file: %v error_location=github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:831) error_op= error_text=Unable to load icon from temp file: The operation completed successfully. error_type=errors.Error]
ERROR systray: systray_windows.go:831   at github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:831)
ERROR systray: systray_windows.go:831   at github.com/mangalaman93/giggle/tray.(*GTray).OnReady (tray.go:70)
ERROR systray: systray_windows.go:831   at github.com/getlantern/systray.Register.func2 (systray.go:89)
ERROR systray: systray_windows.go:831   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:831 Caused by: The operation completed successfully.
ERROR systray: systray_windows.go:861 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861) error_op= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.(*MenuItem).update (systray.go:192)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.AddMenuItem (systray.go:114)
ERROR systray: systray_windows.go:861   at github.com/mangalaman93/giggle/tray.(*GTray).OnReady (tray.go:72)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.Register.func2 (systray.go:89)
ERROR systray: systray_windows.go:861   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:861 Caused by: Invalid menu handle.
ERROR systray: systray_windows.go:831 Unable to load icon from temp file: The operation completed successfully. [error=Unable to load icon from temp file: %v error_location=github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:831) error_op= error_text=Unable to load icon from temp file: The operation completed successfully. error_type=errors.Error]
ERROR systray: systray_windows.go:831   at github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:831)
ERROR systray: systray_windows.go:831   at github.com/mangalaman93/giggle/tray.(*GTray).OnReady (tray.go:73)
ERROR systray: systray_windows.go:831   at github.com/getlantern/systray.Register.func2 (systray.go:89)
ERROR systray: systray_windows.go:831   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:831 Caused by: The operation completed successfully.
```

**Comment by CsterKuroi** [comment]
The same issue

**Comment by jimluo** [comment]
![image](https://user-images.githubusercontent.com/73940/83591208-010e3680-a58a-11ea-8c77-54ddcc0d5627.png)
same error,but work.

**Comment by jwfergus** [comment]
The system call here is returning 0 (error).
https://github.com/getlantern/systray/blob/01dc414284987aa070498fafbcdac794657bf2e1/systray_windows.go#L135

**Comment by psidex** [comment]
ping @joesis

**Comment by joesis** [comment]
Unfortunately we can not reproduce this issue, nor do we see Lantern users report issues relate to this. By some quick Google search this seems mostly happen on Windows 10, and especially when running inside VM. Did you guys see this in VM or not?

**Comment by CsterKuroi** [comment]
@joesis Obviously not

**Comment by jwfergus** [comment]
@joesis - not inside a VM for me. I really suspect something to do w/ submenu code. I forked a stripped down version of similar code w/o submenus, and it's functioning w/o issue.

**Comment by zyvitski** [comment]
I'm having the same issue, on a Windows 10 machine.

> ERROR systray: systray_windows.go:795 Unable to set icon: The operation completed successfully. [error=Unable to set icon: %v error_location=github.com/getlantern/systray.SetIcon (systray_windows.go:795) error_op= error_text=Unable to set icon: The operation completed successfully. error_type=errors.Error]
> ERROR systray: systray_windows.go:795   at github.com/getlantern/systray.SetIcon (systray_windows.go:795)
> ERROR systray: systray_windows.go:795   at main.main.func1 (main.go:29)
> ERROR systray: systray_windows.go:795   at github.com/getlantern/systray.Register.func2 (systray.go:91)
> ERROR systray: systray_windows.go:795   at runtime.goexit (asm_amd64.s:1357)
> ERROR systray: systray_windows.go:795 Caused by: The operation completed successfully.
> ERROR systray: systray_windows.go:853 Unable to set tooltip: Unspecified error [error=Unable to set tooltip: %v error_location=github.com/getlantern/systray.SetTooltip (systray_windows.go:853) error_op= error_text=Unable to set tooltip: Unspecified error error_type=errors.Error]
> ERROR systray: systray_windows.go:853   at github.com/getlantern/systray.SetTooltip (systray_windows.go:853)
> ERROR systray: systray_windows.go:853   at main.main.func1 (main.go:30)
> ERROR systray: systray_windows.go:853   at github.com/getlantern/systray.Register.func2 (systray.go:91)
> ERROR systray: systray_windows.go:853   at runtime.goexit (asm_amd64.s:1357)
> ERROR systray: systray_windows.go:853 Caused by: Unspecified error
> ERROR systray: systray_windows.go:861 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861) error_op= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861)
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.(*MenuItem).update (systray.go:194)
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.AddMenuItem (systray.go:116)
> ERROR systray: systray_windows.go:861   at main.main.func1 (main.go:32)
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.Register.func2 (systray.go:91)
> ERROR systray: systray_windows.go:861   at runtime.goexit (asm_amd64.s:1357)
> ERROR systray: systray_windows.go:861 Caused by: Invalid menu handle.
> ERROR systray: systray_windows.go:877 Unable to addSeparator: Invalid menu handle. [error=Unable to addSeparator: %v error_location=github.com/getlantern/systray.addSeparator (systray_windows.go:877) error_op= error_text=Unable to addSeparator: Invalid menu handle. error_type=errors.Error]
> ERROR systray: systray_windows.go:877   at github.com/getlantern/systray.addSeparator (systray_windows.go:877)
> ERROR systray: systray_windows.go:877   at github.com/getlantern/systray.AddSeparator (systray.go:122)
> ERROR systray: systray_windows.go:877   at main.main.func1 (main.go:33)
> ERROR systray: systray_windows.go:877   at github.com/getlantern/systray.Register.func2 (systray.go:91)
> ERROR systray: systray_windows.go:877   at runtime.goexit (asm_amd64.s:1357)
> ERROR systray: systray_windows.go:877 Caused by: Invalid menu handle.
> ERROR systray: systray_windows.go:861 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861) error_op= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861)
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.(*MenuItem).update (systray.go:194)
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.AddMenuItem (systray.go:116)
> ERROR systray: systray_windows.go:861   at main.main.func1 (main.go:34)
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.Register.func2 (systray.go:91)
> ERROR systray: systray_windows.go:861   at runtime.goexit (asm_amd64.s:1357)
> ERROR systray: systray_windows.go:861 Caused by: Invalid menu handle.

Reading the error it appears that an error is being generated for a return value that is not an error.
What would it take to get this fixed? Do you need a way to reproduce it? or is the issue that it is not affecting your business and don't have a reason to? If it is the later, would you be open to a PR for it?

**Comment by zyvitski** [comment]
I went ahead and implemented a solution. See: #159

**Comment by zyvitski** [comment]
After some more debugging using the included example on my system. I am also getting a different error. In `winTray.setIcon` the call to `t.nid.modify()` is returning a `syscall.Errno` with a numerical value of `2147500037`

**Comment by zyvitski** [comment]
> ERROR systray: systray_windows.go:795 Unable to set icon: Unspecified error [error=Unable to set icon: %v error_location=github.com/getlantern/systray.SetIcon (systray_windows.go:795) error_op= error_text=Unable to set icon: Unspecified error error_type=errors.Error]
> ERROR systray: systray_windows.go:795   at github.com/getlantern/systray.SetIcon (systray_windows.go:795)
> ERROR systray: systray_windows.go:795   at github.com/getlantern/systray.SetTemplateIcon (systray_windows.go:805)
> ERROR systray: systray_windows.go:795   at main.onReady (main.go:23)
> ERROR systray: systray_windows.go:795   at github.com/getlantern/systray.Register.func2 (systray.go:91)
> ERROR systray: systray_windows.go:795   at runtime.goexit (asm_amd64.s:1357)
> ERROR systray: systray_windows.go:795 Caused by: Unspecified error
> ERROR systray: systray_windows.go:853 Unable to set tooltip: Unspecified error [error=Unable to set tooltip: %v error_location=github.com/getlantern/systray.SetTooltip (systray_windows.go:853) error_op= error_text=Unable to set tooltip: Unspecified error error_type=errors.Error]
> ERROR systray: systray_windows.go:853   at github.com/getlantern/systray.SetTooltip (systray_windows.go:853)
> ERROR systray: systray_windows.go:853   at main.onReady (main.go:25)
> ERROR systray: systray_windows.go:853   at github.com/getlantern/systray.Register.func2 (systray.go:91)
> ERROR systray: systray_windows.go:853   at runtime.goexit (asm_amd64.s:1357)
> ERROR systray: systray_windows.go:853 Caused by: Unspecified error
> ERROR systray: systray_windows.go:861 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861) error_op= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861)
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.(*MenuItem).update (systray.go:194)
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.AddMenuItem (systray.go:116)
> ERROR systray: systray_windows.go:861   at main.onReady (main.go:26)
> ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.Register.func2 (systray.go:91)
> ERROR systray: systray_windows.go:861   at runtime.goexit (asm_amd64.s:1357)
> ERROR systray: systray_windows.go:861 Caused by: Invalid menu handle.
> 

And that is the associated error output from that debug session

**Comment by zyvitski** [comment]
After some more testing. I have determined that my issue was related to the fact that I was attempting to use a "png" which works on max, but it appears that windows (or your usage of the winapi, I'm unsure which one) only accepts "ico" files.

To anyone who is trying to use a "png" on windows that may be your issue.

Are the image file restrictions listed somewhere in your docs? if not could they be added?

**Comment by joesis** [comment]
@zyvitski the godoc of `SetIcon` method mentioned the required formats

**Comment by ellis2323** [comment]
Not sure, if it helps but it works for me:

 - add a mutex on two operations: https://github.com/getlantern/systray/commit/5de7ae7061bc9513c809fdc82d53a34c857b49a2

**Comment by subins2000** [comment]
Removing the `SetTooltip` call fixed the crash for me
