### ISSUE TITLE
gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

### ISSUE THREAD

**Issue by dougsland** [getlantern/systray#166]
This go module looks promising but I am facing an issue when running the example or any other function from API. Am I missing any step?

$ go version
go version go1.14.6 linux/amd64

$ rpm -qa | grep gtk3
webkit2gtk3-jsc-2.28.3-1.fc32.x86_64
libindicator-gtk3-12.10.1-17.fc32.x86_64
gtk3-3.24.21-1.fc32.x86_64
spice-gtk3-0.38-1.fc32.x86_64
libreoffice-gtk3-6.4.5.2-5.fc32.x86_64
libappindicator-gtk3-devel-12.10.0-28.fc32.x86_64
gtk3-devel-3.24.21-1.fc32.x86_64
ibus-gtk3-1.5.22-7.fc32.x86_64
libcanberra-gtk3-0.30-22.fc32.x86_64
libappindicator-gtk3-12.10.0-28.fc32.x86_64
libdbusmenu-gtk3-16.04.0-15.fc32.x86_64
webkit2gtk3-2.28.3-1.fc32.x86_64
PackageKit-gtk3-module-1.1.13-3.fc32.x86_64

$ cat /etc/os-release 
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

$ go get  github.com/getlantern/systray
$ cd ~/go/src/github.com/getlantern/systray/example

example>$ env GO111MODULE=on go build
go: finding module for package github.com/skratchdot/open-golang/open
go: found github.com/skratchdot/open-golang/open in github.com/skratchdot/open-golang v0.0.0-20200116055534-eef842397966

example>$ ./example
(example:105730): Gtk-CRITICAL **: 10:52:39.816: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

Same issue happens on Fedora 31.

**Comment by simonsolberg** [comment]
I have this issue with an applet using this library. Installing TopIcons Plus (https://extensions.gnome.org/extension/1031/topicons/) fixed the issue. Not sure whats going on.

**Comment by simonsolberg** [comment]
Apparently they removed the legacy tray in Gnome 3.36: https://bugzilla.gnome.org/show_bug.cgi?id=785956 So using an extension is mandatory for this functionality now.

**Comment by T0maas** [comment]
I have the same issue on gnome wayland, but when I set env variable GDK_BACKEND=x11 it works.
