### ISSUE TITLE
Menu starting with a sub-menu is not correctly rendered

### ISSUE THREAD

**Issue by haxorof** [getlantern/systray#167]
The [example](https://github.com/getlantern/systray/blob/master/example/main.go) in this repo which contains example of how sub-menus can be built. However, if the sub-menu is the first menu item then it does not render it correctly and second level ends up as a top menu item.

This is tested on Windows 10 which Go 1.15 and what changes I tried in the example was to move the lines [47-50](https://github.com/getlantern/systray/blob/master/example/main.go#L47-L50) to above line [26](https://github.com/getlantern/systray/blob/master/example/main.go#L26).

Menu will start like this:
```
SubMenu
SubMenu - Level 2
Quit
...
```

**Comment by joesis** [comment]
Thanks for the finding @haxorof ! How does https://github.com/getlantern/systray/pull/173 work to you?

**Comment by haxorof** [comment]
@joesis LGTM! Verified that the example also worked when I moved the sub-menus above "Quit" as first item.
