### ISSUE TITLE
*MenuItem.Disable() is not working in sub-menu on macOS

### ISSUE THREAD

**Issue by sithembiso** [getlantern/systray#169]
This does not seem to disable the menu element when it is on a sub-menu:
```go
...
options := systray.AddMenuItem("Options")
subCategories := options.AddSubMenuItem("Sub categories", "")
subCategories.Disable()
...
```
This works only when applied to the first level menu item.

**Comment by joesis** [comment]
Which platform did you see this @sithembiso ?

**Comment by sithembiso** [comment]
I mentioned it on the title :-D. It's macOS. Catalina 10.15.4  to be exact.

**Comment by joesis** [comment]
Oops sorry. Looking into it

**Comment by joesis** [comment]
Could you try https://github.com/getlantern/systray/pull/172 @sithembiso ?

**Comment by sithembiso** [comment]
Brilliant! Worked like a charm @joesis! 
Can we get this PR merged, please :-)
