### ISSUE TITLE
unable to run as windows service with winsw

### ISSUE THREAD

**Issue by si458** [getlantern/systray#210]
is it possible to get this to work as a windows service with https://github.com/winsw/winsw?
the example works perfectly fine if run from command line, and even standard exe and double click
but if you try to run it as a service, it is never displayed ???
BUT it is indeed running in the taskmanager?

**Comment by xeijin** [comment]
@si458 probably for the same reason as mentioned in this comment:

https://github.com/hallazzang/hallazzang.github.io/issues/2#issuecomment-546581674 

> Though if you're going to use tray icons in window services, not a user application, you cannot use it directly in your service's code. Because **windows services are not allowed to have user interactions, they cannot have UI themselves, including tray icons**. In that case, you should create a separate user level application and use some IPC techniques to connect it with your service application.

**Comment by si458** [comment]
I'm closing this as it's already discussed it's not possible to use with a windows service as it's must be run as a separate application as the user instead
