### ISSUE TITLE
undefined functions

### ISSUE THREAD

**Issue by jsmyb** [getlantern/systray#211]
../../go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190727060347-6f0e5a3c556c/systray.go:81:2: undefined: nativeLoop
../../go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190727060347-6f0e5a3c556c/systray.go:87:3: undefined: quit
../../go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190727060347-6f0e5a3c556c/systray.go:105:2: undefined: addSeparator
../../go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190727060347-6f0e5a3c556c/systray.go:139:2: undefined: hideMenuItem
../../go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190727060347-6f0e5a3c556c/systray.go:144:2: undefined: showMenuItem
../../go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190727060347-6f0e5a3c556c/systray.go:169:2: undefined: addOrUpdateMenuItem
make: *** [linux] Error 2

**Comment by jugg1es** [comment]
I'm having the same problem

**Comment by egregors** [comment]
Does someone find the solution? I just can't build the project because of this problem

**Comment by jugg1es** [comment]
If you are trying to build for OSX, it appears as though you have to build on OSX.  You can't build cross-platform for OSX from what I can tell.

**Comment by indeedhat** [comment]
my guess would be that you are trying to build with cgo disabled, i did a little test and this is what i see on linux without cgo
