### ISSUE TITLE
Run without .dll

### ISSUE THREAD

**Issue by techtonik** [getlantern/systray#22]
Why .dll is needed? It seems possible to avoid using it or `cgo`.

1. https://github.com/lxn/walk/issues/68 - win GUI toolkit that compiles without `cgo`
2. https://gist.github.com/nathan-osman/18c2e227ad00a223b61c0b3c16d452c3 - WinAPI access from Go
3. https://news.ycombinator.com/item?id=11962359 - thread with links above

**Comment by joesis** [comment]
@techtonik We have no incentive to make the change as Lantern has been using it for quite a long time, but PR is welcome!

**Comment by hugows** [comment]
Is there any downside to using the provided DLLs instead of building DLLs ourselves?

**Comment by meskio** [comment]
Can this issue be closed now that #44 has being merged?

**Comment by Crosse** [comment]
I think this was closed with #43.
