### ISSUE TITLE
Spacing between icons changes (Monterey, M1 Mac with Notch)

### ISSUE THREAD

**Issue by schreibe72** [getlantern/systray#223]
The distance between the icons in the menubar changes as soon as a program is started with this lib. This seems to occur only on monterey and new M1 models with notch. Intel models with the same OS version do not have this problem.
Here screenshots without and with systray.
Before starting systray app:
<img width="736" alt="without_systray" src="https://user-images.githubusercontent.com/9357525/151055652-6b48b08f-342b-4b9b-bb91-73f0af5ce1f4.png">
After starting systray app:
<img width="763" alt="with_systray" src="https://user-images.githubusercontent.com/9357525/151055706-3007eeaa-be34-41aa-b4e7-40a28df59d0a.png">

Any Idea?

**Comment by DVSoftware** [comment]
It is not this library issue, as it should happen with any other app. Known issue on Monterey.

**Comment by Crosse** [comment]
@DVSoftware is it related to [this thread](https://forums.macrumors.com/threads/monterey-menu-bar-icon-spacing.2325987/)?

**Comment by DVSoftware** [comment]
@Crosse yes, that's the issue, but not that thread specifically, I saw it on reddit: https://www.reddit.com/r/mac/comments/qyb7v4/monterey_m1_my_menu_bar_icons_are_randomly/

**Comment by Crosse** [comment]
Another one linked to that Reddit thread, where the OP submitted a bug report to Apple: https://www.reddit.com/r/MacOS/comments/qw83xp/anyone_else_notice_the_menu_bar_status_icon/

Since this appears to be a more general issue with Monterey and the M1 "notched" MBPs, I'm going to close this.
