### ISSUE TITLE
not working in Fedora 25

### ISSUE THREAD

**Issue by sp-joseluis-ledesma** [getlantern/systray#23]
In Fedora 25 (Gnome3) the tray icon does not show up. I have installed topicons extension, and other tray icons are shown (slack for example).

I don't know if it is gnome3 or wayland related.

**Comment by joesis** [comment]
@sp-joseluis-ledesma are you running the example? could you describe the detailed steps? Did you install the [depedencies](https://github.com/getlantern/systray#linux)? Sorry we don't have this specific environment to try.

**Comment by sp-joseluis-ledesma** [comment]
Yes, I did install the dependencies and the example does not work. It runs but no icon is showed in the systray.

**Comment by vith** [comment]
I think libappindicator's GtkStatusIcon fallback just doesn't work, I have the same problem with https://github.com/phocean/TopIcons-plus on Fedora or Arch.

This seems to be the upstream bug: https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/1086656

The example does work with the appindicator gnome shell extension, however: https://github.com/Ubuntu/gnome-shell-extension-appindicator

Note that GtkStatusIcon has been deprecated for a while and will be removed in a future version: https://github.com/GNOME/gtk/commit/d2a8667f835ddce4ac88b9bee143556f9efa93c4

**Comment by bcmertz** [comment]
I was only able to replicate this bug by installing libappindicator without the -dev suffix. Even from clean installation of Ubuntu 18.04 running Gnome3 installing the recommended dependencies `sudo apt install libgtk-3-dev and libappindicator3-dev` appears to work as expected. It appears maybe the non *-dev appindicator packages no longer contain all the appindicator bindings needed to support system tray icons now that Ubuntu doesn't support system tray
