### ISSUE TITLE
How do we make a dock icon do something interesting when clicked?

### ISSUE THREAD

**Issue by OptimisticLock** [getlantern/systray#239]
There is a large app icon sitting in the dock on Mac. We could remove it, but we'd prefer it to do something interesting, e.g. open a popup or a window. Any way to do that?

**Comment by OptimisticLock** [comment]
Sorry, please disregard. I didn't RTFM. Here is the answer.
```
On macOS, you will need to create an application bundle to wrap the binary; simply use "fyne package" or add folders with the following minimal structure and assets:

SystrayApp.app/
  Contents/
    Info.plist
    MacOS/
      go-executable
    Resources/
      SystrayApp.icns
When running as an app bundle, you may want to add one or both of the following to your Info.plist:

<!-- avoid having a blurry icon and text -->
	<key>NSHighResolutionCapable</key>
	<string>True</string>

	<!-- avoid showing the app on the Dock -->
	<key>LSUIElement</key>
	<string>1</string>
Consult the [Official Apple Documentation here](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1).
```
https://libraries.io/go/github.com%2FfuqiangZ%2Fsystray

**Comment by Crosse** [comment]
This library is for adding an icon to the system tray (the menu bar, on macOS); it doesn't do anything fancy with dock icons. You'll need to handle that in your app's code, I think.

**Comment by OptimisticLock** [comment]
Would it be possible to have the dock icon behave identically to the system tray icon? I can just imagine no purpose for it otherwise.
