### ISSUE TITLE
Ballon Message from Tray Icon

### ISSUE THREAD

**Issue by juliardi** [getlantern/systray#38]
Is it possible to show a ballon message from systray? 
For example like this :
![screenshot_20180126_171105](https://user-images.githubusercontent.com/4223302/35435120-18445b40-02bc-11e8-8d1e-595777f90742.png)

**Comment by meskio** [comment]
@juliardi AFAIK not, what I'm doing is to use another library for that:
https://github.com/0xAX/notificator

**Comment by juliardi** [comment]
@meskio thanks for your answer and reference, I'll try using that library
