### ISSUE TITLE
MVE:Skipping file IMG000.jpg, cannot load image.

### ISSUE THREAD

**Issue by lanlan2015** [getlantern/systray#4]
when I use makescene,the code as follows：
cp@cp-virtual-machine:~/pan/mve/apps/makescene$ ./makescene -o -i /home/cp/pan/mve/apps/makescene/images /home/cp/pan/mve/apps/makescene/mm
Found 1 directory entries.
Creating output directories...
Importing image IMG000.jpg...
Skipping file IMG000.jpg, cannot load image.
Imported 0 input images.
how to solve this problem?

**Comment by fffw** [comment]
@lanlan2015 Are you posting to wrong repo?

**Comment by lanlan2015** [comment]
If I change the JPG picture to  TIFF picture，it can be compiled successfully。I don't know why？@fffw

**Comment by fffw** [comment]
@lanlan2015 You didn't post any compilation error of `systray`. I have no idea what `makescene` is.

**Comment by lanlan2015** [comment]
I have found the way。Thanks for you help

**Comment by lanlan2015** [comment]
I have found the way.Thanks for you help.@fffw

**Comment by fffw** [comment]
Great. Hope you are doing well.
