### ISSUE TITLE
Please fork getlantern/stack from latest go-stack to enable debugging with delve

### ISSUE THREAD

**Issue by theliebeskind** [getlantern/systray#57]
Currently, trying to debug a project that uses systray fails with "bad access" (see https://github.com/derekparker/delve/issues/975).

This can be fixed by use the latest version of github.com/go-stack/stack (which you forked for getlantern/stack).

I tested it locally by replacing it in getlantern/errors and it worked.

Thanks!

**Comment by joesis** [comment]
Thanks @theliebeskind! Created https://github.com/getlantern/errors/pull/3 to ditch `getlantern/stack`. Waiting for peer review.
