### ISSUE TITLE
OSX Mojave warnings...

### ISSUE THREAD

**Issue by pknudsgaard** [getlantern/systray#75]
Upgraded my laptop to Mojave and I am getting the following warnings:

# vendor/github.com/getlantern/systray
systray_darwin.m:67:15: warning: 'setImage:' is deprecated: first deprecated in macOS 10.14 - Use the receiver's button.image instead [-Wdeprecated-declarations]
/System/Library/Frameworks/AppKit.framework/Headers/NSStatusItem.h:85:39: note: property 'image' is declared deprecated here
/System/Library/Frameworks/AppKit.framework/Headers/NSStatusItem.h:85:39: note: 'setImage:' has been explicitly marked deprecated here
systray_darwin.m:71:15: warning: 'setTitle:' is deprecated: first deprecated in macOS 10.14 - Use the receiver's button.title instead [-Wdeprecated-declarations]
/System/Library/Frameworks/AppKit.framework/Headers/NSStatusItem.h:83:38: note: property 'title' is declared deprecated here
/System/Library/Frameworks/AppKit.framework/Headers/NSStatusItem.h:83:38: note: 'setTitle:' has been explicitly marked deprecated here
systray_darwin.m:75:15: warning: 'setToolTip:' is deprecated: first deprecated in macOS 10.14 - Use the receiver's button.toolTip instead [-Wdeprecated-declarations]
/System/Library/Frameworks/AppKit.framework/Headers/NSStatusItem.h:89:38: note: property 'toolTip' is declared deprecated here
/System/Library/Frameworks/AppKit.framework/Headers/NSStatusItem.h:89:38: note: 'setToolTip:' has been explicitly marked deprecated here
systray_darwin.m:105:24: warning: 'NSOnState' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
/System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:80:34: note: 'NSOnState' has been explicitly marked deprecated here
systray_darwin.m:107:24: warning: 'NSOffState' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
/System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:79:34: note: 'NSOffState' has been explicitly marked deprecated here

**Comment by joesis** [comment]
It should have been fixed by https://github.com/getlantern/systray/pull/66. @pknudsgaard did you pull the latest `master`?

**Comment by raunaqrox** [comment]
I'm getting the following warnings

```
# github.com/getlantern/systray
systray_darwin.m:128:22: warning: 'NSOnState' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
systray_darwin.m:9:33: note: expanded from macro 'NSControlStateValueOn'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:80:34: note: 'NSOnState' has been explicitly marked deprecated here
systray_darwin.m:130:22: warning: 'NSOffState' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
systray_darwin.m:5:34: note: expanded from macro 'NSControlStateValueOff'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:79:34: note: 'NSOffState' has been explicitly marked deprecated here
```

**Comment by artheus** [comment]
I am getting the same warnings as @raunaqrox.
In addition to this, my app will panic whenever I use `systray.Run(onReady, onExit)`, this is the panic error message:
```
2019-06-02 10:44:41.745 ___go_build_main_go[22553:5250230] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1570.16/Foundation/Misc.subproj/NSUndoManager.m:361
2019-06-02 10:44:41.746 ___go_build_main_go[22553:5250230] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2e1a8cf9 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff58d38a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2e1c3a16 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff30455e11 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Foundation                          0x00007fff30388e7c +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 473
	5   AppKit                              0x00007fff2b771f89 -[NSApplication run] + 916
	6   ___go_build_main_go                 0x0000000004280170 nativeLoop + 128
	7   ___go_build_main_go                 0x000000000427f67a _cgo_67d7e7d56c36_Cfunc_nativeLoop + 26
	8   ___go_build_main_go                 0x0000000004058e60 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff5a6a12c6 m=6 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x427f660, 0xc0000e9e88, 0xc000000101)
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc0000e9e58 sp=0xc0000e9e20 pc=0x40051bb
github.com/getlantern/systray._Cfunc_nativeLoop(0x0)
	_cgo_gotypes.go:107 +0x49 fp=0xc0000e9e88 sp=0xc0000e9e58 pc=0x427eab9
github.com/getlantern/systray.nativeLoop(...)
	/Users/artheus/go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190131073753-26d5b920200d/systray_nonwindows.go:19
github.com/getlantern/systray.Run(0x4330db8, 0x4330db0)
	/Users/artheus/go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190131073753-26d5b920200d/systray.go:81 +0x7f fp=0xc0000e9ec0 sp=0xc0000e9e88 pc=0x427e7ff
main.main()
	/Users/artheus/go/src/github.com/artheus/gopdate/main.go:16 +0x20d fp=0xc0000e9f98 sp=0xc0000e9ec0 pc=0x427f3bd
runtime.main()
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:200 +0x20c fp=0xc0000e9fe0 sp=0xc0000e9f98 pc=0x402f29c
runtime.goexit()
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000e9fe8 sp=0xc0000e9fe0 pc=0x40596c1

goroutine 20 [chan receive]:
github.com/getlantern/systray.Run.func2(0xc0000862a0, 0x4330db8)
	/Users/artheus/go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190131073753-26d5b920200d/systray.go:66 +0x34
created by github.com/getlantern/systray.Run
	/Users/artheus/go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190131073753-26d5b920200d/systray.go:65 +0xf1

rax    0x0
rbx    0x70000dc82000
rcx    0x70000dc80488
rdx    0x0
rdi    0xb03
rsi    0x6
rbp    0x70000dc804c0
rsp    0x70000dc80488
r8     0x70000dc80350
r9     0x70000dc80520
r10    0x0
r11    0x206
r12    0xb03
r13    0x3000000008
r14    0x6
r15    0x2d
rip    0x7fff5a6a12c6
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
```

**Comment by raunaqrox** [comment]
@artheus Could you show your code, I had similar issue but that was due to me using nil values when onReady was not done. For reference I'm using systray here github.com/promignis/cwitch.

**Comment by scottgrobinson** [comment]
@artheus I had the same issue which was resolved by adding
`runtime.LockOSThread()`

as pe https://github.com/getlantern/systray/issues/20

**Comment by mikeschinkel** [comment]
We are getting the same issues as @raunaqrox where `'NSOnState' is deprecated:`

**Comment by mikeschinkel** [comment]
I *may* have solved this with the following wrapper code to replace lines `4`-`10` of `systray_darwin.m`.  

```
#if __MAC_OS_X_VERSION_MIN_REQUIRED < __MAC_10_14
    #ifndef NSControlStateValueOff
      #define NSControlStateValueOff NSOffState
    #endif
    #ifndef NSControlStateValueOn
      #define NSControlStateValueOn NSOnState
    #endif
#endif
```

I will be submit a pull request with this code.
