### ISSUE TITLE
cannot build,at macOS 10.14 

### ISSUE THREAD

**Issue by chengziqing** [getlantern/systray#83]
NSOffState is Obsolete

**Comment by joesis** [comment]
@chengziqing The latest master doesn't use `NSOffState`.

**Comment by chengziqing** [comment]
@joesis The latest master "systray_darwin.m"，Still in use NSOffState。You can have a look at the file.
At macOS 10.13 can build.

**Comment by joesis** [comment]
@chengziqing do you mean https://github.com/getlantern/systray/blob/master/systray_darwin.m#L5? It's for compatibility. I can build on 10.14.3 without issue. Can you post the toolchain versions and full error message?

**Comment by chengziqing** [comment]
@joesis 
cd getlantern/systray/example
go build

systray_darwin.m:128:22: warning: 'NSOnState' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
systray_darwin.m:9:33: note: expanded from macro 'NSControlStateValueOn'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:80:34: note: 'NSOnState' has been explicitly marked deprecated here
systray_darwin.m:130:22: warning: 'NSOffState' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
systray_darwin.m:5:34: note: expanded from macro 'NSControlStateValueOff'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:79:34: note: 'NSOffState' has been explicitly marked deprecated here

**Although it can be compiled in macOS 10.14 , but in macOS 10.13, it cannot be installed via dmg.**

**Comment by joesis** [comment]
@chengziqing No the warning is not the cause of the installation problem, as long as the binary can run there.
