### ISSUE TITLE
go 1.13 : build command-line-arguments: cannot load bufio: malformed module path "bufio": missing dot in first path element

### ISSUE THREAD

**Issue by i6du** [getlantern/systray#93]
go version go1.13beta1 darwin/amd64

go: finding github.com/getlantern/systray latest
go: finding github.com/skratchdot/open-golang latest
go: finding github.com/getlantern/golog latest
go: finding github.com/getlantern/ops latest
go: finding github.com/getlantern/errors latest
go: finding github.com/getlantern/hidden latest
go: finding github.com/oxtoacart/bpool latest
go: finding github.com/getlantern/hex latest
go: finding github.com/getlantern/context latest
build command-line-arguments: cannot load bufio: malformed module path "bufio": missing dot in first path element

**Comment by joesis** [comment]
@i6du are you sure you are ticketing on the correct repo?
