### ISSUE TITLE
cannot build at macOS 10.12

### ISSUE THREAD

**Issue by antwal** [getlantern/systray#95]
Build error:

# github.com/getlantern/systray
systray_darwin.m:132:22: error: use of undeclared identifier 'NSControlStateValueOn'
systray_darwin.m:134:22: error: use of undeclared identifier 'NSControlStateValueOff'

pls fix retro compatibility

**Comment by joesis** [comment]
https://github.com/getlantern/systray/pull/94 (thank @teddywing !) should have fixed it. @antwal could you try get the latest master?

**Comment by antwal** [comment]
I'm testing, I'll answer you on the PR
